// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginUploadResumenSelectResumenToUpLoadSelectFileTypeUploadSearchCatalogCheckUploadedResumeLogOutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginUploadResumenSelectResumenToUpLoadSelectFileTypeUploadSearchCatalogCheckUploadedResumeLogOut() {
    driver.get("http://128.140.65.83/");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_logoutButton_1rsts_161")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("test@selenium.es");
    driver.findElement(By.cssSelector(".\\_header_1b7ei_1")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("testtest");
    driver.findElement(By.cssSelector(".\\_header_1b7ei_1")).click();
    driver.findElement(By.cssSelector(".\\_button_12z9i_3")).click();
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_writerButton_1rsts_193")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("Prueba Selenium");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.cssSelector("input:nth-child(4)")).sendKeys("Resumen para prueba de Sistema con Selenium - Escritor");
    {
      WebElement element = driver.findElement(By.cssSelector("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector("select")).click();
    driver.findElement(By.cssSelector("option:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".\\_fileInput_b08uj_75")).click();
    driver.findElement(By.cssSelector(".\\_fileInput_b08uj_75")).click();
    driver.findElement(By.cssSelector(".\\_fileInput_b08uj_75 > label")).click();
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("C:\\fakepath\\Prueba de Sistema con Selenium.pdf");
    driver.findElement(By.cssSelector(".\\_submit_b08uj_101")).click();
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(2) > .\\_label_1l7d2_117")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_active_1l7d2_125 > .\\_label_1l7d2_117"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".\\_input_p4csh_69")).click();
    driver.findElement(By.cssSelector(".\\_input_p4csh_69")).sendKeys("prueba ");
    driver.findElement(By.cssSelector(".\\_cover_9faw8_19")).click();
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(3) > .\\_label_1l7d2_117")).click();
    driver.findElement(By.cssSelector(".\\_logoutButton_1rsts_161")).click();
  }
}
