// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterSubscriptionSearchFilterReadIAListenCommentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerSubscriptionSearchFilterReadIAListenComment() {
    driver.get("http://128.140.65.83/");
    driver.manage().window().setSize(new Dimension(1292, 732));
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_logoutButton_1rsts_161")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".\\_switchLink_9gh27_41")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("test@selenium.es");
    driver.findElement(By.id("password")).sendKeys("testtest");
    driver.findElement(By.cssSelector(".\\_form_1h7p7_3")).click();
    driver.findElement(By.cssSelector(".\\_toggle_1i06m_3")).click();
    driver.findElement(By.cssSelector(".\\_button_12z9i_3")).click();
    driver.close();
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_item_1l7d2_65:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".\\_input_p4csh_69")).click();
    driver.findElement(By.cssSelector(".\\_input_p4csh_69")).sendKeys("ejemplo resumen");
    driver.findElement(By.cssSelector(".\\_input_p4csh_69")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".\\_toggle_1wnhx_29")).click();
    driver.findElement(By.cssSelector(".\\_section_1wnhx_101:nth-child(1) label:nth-child(2) > input")).click();
    driver.findElement(By.cssSelector(".\\_section_1wnhx_101:nth-child(1) label:nth-child(1) > input")).click();
    driver.findElement(By.cssSelector(".\\_section_1wnhx_101:nth-child(3) label:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".\\_section_1wnhx_101:nth-child(3) label:nth-child(1) > input")).click();
    driver.findElement(By.cssSelector(".\\_arrow_1wnhx_67")).click();
    driver.findElement(By.cssSelector(".\\_card_9faw8_1:nth-child(2) > .\\_cover_9faw8_19")).click();
    driver.findElement(By.cssSelector(".\\_texto_1jm1k_81")).click();
    driver.findElement(By.cssSelector(".\\_btn_rf1mq_103:nth-child(3) > svg")).click();
    driver.findElement(By.cssSelector(".\\_btn_rf1mq_103:nth-child(3) > svg")).click();
    driver.findElement(By.cssSelector(".\\_playBtn_rf1mq_139")).click();
    driver.findElement(By.cssSelector(".\\_textarea_14jhp_53")).click();
    driver.findElement(By.cssSelector(".\\_textarea_14jhp_53")).sendKeys("Muy interesante!");
    driver.findElement(By.cssSelector(".\\_starEmpty_14jhp_41:nth-child(5) > path")).click();
    driver.findElement(By.cssSelector(".\\_starFilled_14jhp_29:nth-child(4) > path")).click();
    driver.findElement(By.cssSelector(".\\_submitBtn_14jhp_95")).click();
  }
}
